import type { MenuData } from "./menu.types";

export const fishStationMenu: MenuData = {
  categories: [
    {
      id: "cat-fish-snacks",
      name: "Fish Snacks",
      slug: "fish-snacks",
      description: "Quick seafood bites packed with flavor.",
    },
    {
      id: "cat-main-course",
      name: "Main Course",
      slug: "main-course",
      description: "Hearty seafood dishes for lunch and dinner.",
    },
    {
      id: "cat-sides",
      name: "Sides",
      slug: "sides",
      description: "Perfect add-ons for your meal.",
    },
  ],
  items: [
    {
      id: "item-whole-grill-fish",
      categoryId: "cat-fish-snacks",
      name: "Whole Grill Fish",
      slug: "whole-grill-fish",
      shortDescription: "Fresh grilled fish with signature house spices.",
      description: "A smoky grilled whole fish finished with house masala.",
      imageUrl: "/images/fishstation/whole-grill-fish.jpg",
      price: 850,
      isSpicy: true,
      isFeatured: true,
      isAvailable: true,
    },
    {
      id: "item-fish-choila",
      categoryId: "cat-fish-snacks",
      name: "Fish Choila",
      slug: "fish-choila",
      shortDescription: "Smoky Nepali-style fish choila with herbs and spice.",
      imageUrl: "/images/fishstation/fish-choila.jpg",
      price: 450,
      isSpicy: true,
      isFeatured: true,
      isAvailable: true,
    },
    {
      id: "item-fish-fry",
      categoryId: "cat-fish-snacks",
      name: "Fish Fry",
      slug: "fish-fry",
      shortDescription: "Lightly crispy fish fry with house seasoning.",
      imageUrl: "/images/fishstation/fish-fry.jpg",
      price: 520,
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "item-fish-gravy",
      categoryId: "cat-main-course",
      name: "Fish Gravy",
      slug: "fish-gravy",
      shortDescription: "Rich and comforting fish curry served hot.",
      imageUrl: "/images/fishstation/fish-gravy.jpg",
      price: 650,
      isFeatured: true,
      isAvailable: true,
    },
    {
      id: "item-fish-thali",
      categoryId: "cat-main-course",
      name: "Fish Thali",
      slug: "fish-thali",
      shortDescription: "A complete meal with fish curry, rice, and sides.",
      imageUrl: "/images/fishstation/fish-thali.jpg",
      price: 780,
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "item-steamed-rice",
      categoryId: "cat-sides",
      name: "Steamed Rice",
      slug: "steamed-rice",
      shortDescription: "Soft steamed rice to pair with your seafood dishes.",
      imageUrl: "/images/fishstation/steamed-rice.jpg",
      price: 180,
      isAvailable: true,
    },
    {
      id: "item-fried-potato",
      categoryId: "cat-sides",
      name: "Fried Potato",
      slug: "fried-potato",
      shortDescription: "Crispy golden potato bites with light seasoning.",
      imageUrl: "/images/fishstation/fried-potato.jpg",
      price: 220,
      isAvailable: true,
    },
  ],
};